name: Update RSS Feed

on:
  schedule:
    - cron: '0 12 * * 0'  # Runs every Sunday at 12:00 UTC
  workflow_dispatch:      # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Generate feed.xml
        run: |
          python3 <<EOF
          import requests
          from bs4 import BeautifulSoup
          from datetime import datetime
          import re

          url = "https://gsradio.net/shows/divided_kingdom/"
          response = requests.get(url)
          soup = BeautifulSoup(response.text, 'html.parser')

          links = soup.find_all('a', href=True)
          audio_links = [a['href'] for a in links if a['href'].endswith('.mp3')]

          def extract_date(filename):
              match = re.search(r'/(\d{6})\.mp3$', filename)
              if match:
                  try:
                      return datetime.strptime(match.group(1), '%m%d%y')
                  except:
                      return None
              return None

          seen_files = set()
          items = []

          for link in audio_links:
              filename = link.split('/')[-1]
              if filename in seen_files:
                  continue
              seen_files.add(filename)

              date = extract_date(link)
              if not date:
                  continue

              https_link = link.replace("mms://", "https://")
              pub_date = date.strftime('%a, %d %b %Y 00:00:00 GMT')
              title = f"Episode - {date.strftime('%m/%d/%y')}"
              item = f"""
              <item>
                <title>{title}</title>
                <link>{https_link}</link>
                <guid isPermaLink="false">{https_link}</guid>
                <pubDate>{pub_date}</pubDate>
                <enclosure url="{https_link}" length="12345678" type="audio/mpeg" />
              </item>
              """
              items.append((date, item.strip()))

          items.sort(reverse=True)
          item_xml = "\n".join([item for _, item in items])

          rss_feed = f"""<?xml version="1.0" encoding="UTF-8" ?>
          <rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
            <channel>
              <title>Divided Kingdom</title>
              <link>https://gsradio.net/shows/divided_kingdom/</li_
